### ISSUE TITLE
Download Linked Screencasts

### ISSUE THREAD

**Issue by psuet** [Romern/syncMyMoodle#10]
The tool should also download Screencasts linked to the streaming server:

`<a class="aalink" onclick="" href="https://moodle.rwth-aachen.de/mod/url/view.php?id=36[...]"><img src="[...]" class="iconlarge activityicon" alt="" role="presentation" aria-hidden="true"><span class="instancename">Link to Video<span class="accesshide "> Link/URL</span></span></a>`

which itself links to

`https://engage.streaming.rwth-aachen.de/paella/ui/watch.html?id=[...]`

This setup is unfortunate because the script would have to check every linked resource provided. The feature could also support downloading files "behind" links with specific MIME-types (i.e., PDF, etc.)

**Comment by Romern** [comment]
URLs are automatically downloaded if they are not HTML pages. I added a check if it is an opencast video in https://github.com/Romern/syncMyMoodle/commit/b72c9311d24608af5e8d4abee6b97a3bc9eeaed5 . Could you check if it works?

**Comment by psuet** [comment]
Works perfectly
