### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by OsziBatyam** [Romern/syncMyMoodle#102]
Without changing anything, I started getting this issue:

Logging in...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\olive\env\Lib\site-packages\syncmymoodle\__main__.py", line 1185, in <module>
    main()
  File "C:\Users\olive\env\Lib\site-packages\syncmymoodle\__main__.py", line 1175, in main
    smm.login()
  File "C:\Users\olive\env\Lib\site-packages\syncmymoodle\__main__.py", line 183, in login
    self.session.cookies.update(pickle.load(f))
                                ^^^^^^^^^^^^^^
EOFError: Ran out of input

(sorry if this not the right the place to post this or so, don't have much experience with github)

**Comment by n0toose** [comment]
> (sorry if this not the right the place to post this or so, don't have much experience with github)

Absolutely is, thanks for reporting this!

**Comment by n0toose** [comment]
> Without changing anything

Just to be sure, which authentication provider do you use by default?

**Comment by Romern** [comment]
This sometimes happened when the session file was corrupt, try deleting the ./session file.

**Comment by OsziBatyam** [comment]
I use the config file since I'm on Windows (tried also directly in the command but also doesn't help)


> > Without changing anything
> 
> Just to be sure, which authentication provider do you use by default?

**Comment by OsziBatyam** [comment]
> This sometimes happened when the session file was corrupt, try deleting the ./session file.

didn't help unfortunately

**Comment by OsziBatyam** [comment]
> > This sometimes happened when the session file was corrupt, try deleting the ./session file.
> 
> didn't help unfortunately

Found another session file and deleting that one solved it, thank you for the help

(and btw, when i was having trouble I tried uninstalling and then installing again to see if it would help, and when i was following the instructions in noticed they are only for linux (on the linked python website there are the ones for windows)
