### ISSUE TITLE
Youtube streams prevent script termination

### ISSUE THREAD

**Issue by nilshee** [Romern/syncMyMoodle#114]
If there are currently running youtube streams in a moodle room the script won't terminate since ytdlp will continue to download the stream. 

It should be checked if the youtube link contains a currently running livestream.

**Comment by septatrix** [comment]
> It should be checked if the youtube link contains a currently running livestream.

Can this be easily checked? I have no such URL available currently. ytdlp seems to offer some flags regarding livestream but none for skipping them as far as I can see.

**Comment by nilshee** [comment]
> > It should be checked if the youtube link contains a currently running livestream.
> 
> Can this be easily checked? I have no such URL available currently. ytdlp seems to offer some flags regarding livestream but none for skipping them as far as I can see.

Found a possible solution and opened a pul request
