### ISSUE TITLE
Regularly check for updates

### ISSUE THREAD

**Issue by juliusrickert** [Romern/syncMyMoodle#14]

**Comment by septatrix** [comment]
Personally I think automatic updates should be done from outside this script. For example by performing a simple `git fetch`. There are multiple factors which make this hard from inside a script. E.g. `git fetch` would not work if one only downloaded the ZIP etc. Also it is quite annoying to use/parse the github api/page for such a small feature.

I am currently working on publishing this to pypi. Once that is done a `pip install [--user] --upgrade syncmymoodle` would also work and simultaneously take care of all the other stuff like dependencies. You can also setup a cronjob/sytemd-timer/schtasks which automatically updates this script.

**Comment by juliusrickert** [comment]
Fixed in #71.
