### ISSUE TITLE
Opencast in Moodle Folder

### ISSUE THREAD

**Issue by NiklasVousten** [Romern/syncMyMoodle#23]
Opencast Videos are not downloading in a Folder. Maybe because pdfs are present
![Bildschirmfoto von 2020-11-25 12-13-24](https://user-images.githubusercontent.com/24965952/100220822-27e56e00-2f18-11eb-87f1-9971ac2ad851.png)

**Comment by Romern** [comment]
Should be fixed with https://github.com/Romern/syncMyMoodle/commit/972738b6a486943fab0e7d0180938cf91afe68b3 .

**Comment by NiklasVousten** [comment]
Files can now be downloaded. Maybe add to the Folder. Currently the Video of Flipped Classroom will be saved to the Parent folder of 'Aufgabe_4_2.pdf'

**Comment by Romern** [comment]
I fixed it in https://github.com/Romern/syncMyMoodle/commit/14b96400969b909c9bc4329d57eb8e68c5dde59c
