### ISSUE TITLE
YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by autoantwort** [Romern/syncMyMoodle#39]
I get the following error when running syncMyMoodle:
```
...
[youtube] Ov4dob7_aP8: Downloading webpage
ERROR: Ov4dob7_aP8: YouTube said: Unable to extract video data
...
```
Do you need more information? :)

**Comment by Romern** [comment]
This is a youtube-dl problem, maybe your version is not up to date (the video works for me). Use your package manager (or `pip install --upgrade youtube-dl`) to update the package.

**Comment by autoantwort** [comment]
Thank you! `pip install --upgrade youtube-dl` did the job. Works now 🎉
