### ISSUE TITLE
Some video files are being skipped

### ISSUE THREAD

**Issue by mehmet-safak** [Romern/syncMyMoodle#45]
Since last update, I'm missing some of the videos. 
I couldn't identify a pattern tho
But it affects 'plain' Moodle videos without this puzzle icon

**Comment by mehmet-safak** [comment]
As it can be seen, from 19 video files, only 13 are downloaded

![image](https://user-images.githubusercontent.com/31712384/118919324-968a0e00-b934-11eb-87c8-db47b97f01a3.png)

**Comment by Romern** [comment]
its likely that the filenames might be identical, i.e. zoom_0.mp4. If yes, then someone would need to fix https://github.com/Romern/syncMyMoodle/issues/35

**Comment by Romern** [comment]
Could you try https://github.com/Romern/syncMyMoodle/commit/ea17a29d741d5fca17f6175aeef5305bf4ce482e ?

**Comment by mehmet-safak** [comment]
Looks good to me. All files are named after the moodle title, right?

**Comment by septatrix** [comment]
> Looks good to me. All files are named after the moodle title, right?

A bit simplified but in most cases yes. There are some exceptions though. Among them is special handling for name clashed which might be the root cause of you problem and should have been resolved since the linked commit.

So is this issue still present or can this be closed?

**Comment by mehmet-safak** [comment]
Yes indeed, this can be closed. Thanks
